# Generated by Django 5.1.1 on 2024-09-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_enlistment', '0003_delete_enrollment'),
        ('course_enrollment', '0002_enrollment_course_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_enlistment.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
