# Generated by Django 5.1 on 2024-08-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_enlistment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
