# Generated by Django 5.1 on 2024-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_enlistment', '0002_remove_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='course_image'),
        ),
    ]
