# Generated by Django 5.1.1 on 2024-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_enlistment', '0002_remove_course_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
