# Generated by Django 5.1.1 on 2024-09-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_enlistment', '0003_delete_enrollment'),
        ('course_enlistment', '0004_alter_course_course_image'),
    ]

    operations = [
    ]
