# Generated by Django 5.1.1 on 2024-09-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_enlistment", "0007_course_duration_course_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
    ]
