# Generated by Django 5.1 on 2024-08-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='room_name',
        ),
    ]
