# Generated by Django 5.1 on 2024-08-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_rename_room_message_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_name',
            new_name='room',
        ),
    ]
